[package]
name = "navikaf_rust_api"
version = "0.1.0"
edition = "2021"

[dependencies]
rdkafka = { version = "0.36.2", features = ["cmake-build", "tokio", "futures-executor"] }
chrono = "0.4.37"
log = "0.4.21"
env_logger = "0.11.3"
